### ISSUE TITLE
Revise appointment_report to be person focused

### ISSUE THREAD

**Issue by pbchase** [ctsit/covid19_reporting#5]
Revise appointment_report to be person focused instead of test focused. We should see only one record per in the demographics data. When the multiple (re)test records are summarized, the rule needs to be "covid19_swab_result = max(covid19_swab_result)". 

After making the change I think we need a different test-centric report. I'm not yet sure what that should be.  I think it needs to quantify the _volume_ of testing. It could provide a histogram of the number of tests per person. I am open to suggestion. @senrabc, what do you think the _test_ report should look like?

**Comment by ljwoodley** [comment]
I agree with @pbchase. This report is getting a bit blurry. Maybe we can create a separate section in this report strictIy for appointment reporting. I also feel we may need to report on subjects that retested. Maybe whether or not the covid status changed between tests might be of interest?

**Comment by ljwoodley** [comment]
Addressed by PR #6
