### ISSUE TITLE
Create a report to identify people with duplicate email addresses

### ISSUE THREAD

**Issue by pbchase** [ctsit/covid19_reporting#7]
Create a report to identify people in the First Responder's project with duplicate email addresses. This report needs to be written and tested by 5 p.m. on May 6th.

This report should have a few outputs:

1. an enumeration of every record that, when grouped by email address has a tally >= 2
2. an enumeration of item 1 filtered for record_id != min(record_id)
3. a dataset suitable for import into REDCap that will set email address to "" for every record in item 2. 

The fields for item 3 should be--I think--record_id, redcap_event_name, email_address, though "email_address" is probably something like "ce_email"

**Comment by ljwoodley** [comment]
answered by PR #8
